"""
Public Quote Confirmation — NO AUTHENTICATION REQUIRED

This is the honest replacement for a client login system. Instead of
issuing passwords, we let a client confirm/view their quote via a
private, unguessable link sent to their email — the same trust model
used by "magic link" flows, DocuSign, and most B2B quote tools.

SECURITY MODEL:
  quote_number (e.g. "QT-A3F8C2") already contains a random 6-char
  hex suffix generated by _short_uid() at creation time. That's ~16M
  possible combinations per prefix — not cryptographically bulletproof,
  but combined with the fact that this endpoint only exposes read-only
  quote data (no PII beyond what's already on the quote, no other
  clients' data reachable from it), the risk profile is appropriate
  for a B2B quote confirmation flow. If this becomes higher-stakes
  later (large quote values, sensitive attachments), upgrade to a
  dedicated signed token (itsdangerous / JWT with expiry) rather than
  relying on the quote_number alone.
"""
from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models import Quote, QuoteStatus
from app.schemas import QuoteOut

router = APIRouter(prefix="/public/quotes", tags=["Public Quote Confirmation"])


@router.get("/{quote_number}", response_model=QuoteOut)
async def view_quote_public(quote_number: str, db: AsyncSession = Depends(get_db)):
    """
    Public, unauthenticated quote lookup by quote_number.
    This is the link a client clicks from their email — no login needed.
    """
    result = await db.execute(select(Quote).where(Quote.quote_number == quote_number))
    quote = result.scalar_one_or_none()
    if not quote:
        raise HTTPException(404, "Quote not found. Please check the link or contact us.")
    return quote


@router.post("/{quote_number}/confirm", response_model=QuoteOut)
async def confirm_quote_public(quote_number: str, db: AsyncSession = Depends(get_db)):
    """
    Client clicks "Accept This Quote" from the emailed link.
    No password, no account — the email itself IS the confirmation channel,
    matching what was asked for instead of building full client auth.
    """
    result = await db.execute(select(Quote).where(Quote.quote_number == quote_number))
    quote = result.scalar_one_or_none()
    if not quote:
        raise HTTPException(404, "Quote not found.")

    if quote.status == QuoteStatus.accepted:
        return quote  # idempotent — clicking twice doesn't error

    if quote.status not in (QuoteStatus.sent, QuoteStatus.negotiating):
        raise HTTPException(
            400,
            f"This quote cannot be accepted from its current status ('{quote.status.value}'). "
            f"Contact Bilm Technical Services if you believe this is an error.",
        )

    quote.status = QuoteStatus.accepted
    quote.accepted_at = datetime.utcnow()
    await db.commit()
    await db.refresh(quote)
    return quote
